import { createHash, timingSafeEqual } from 'node:crypto';
import { z } from 'zod';
import { databasePool } from './postgres';
import { envelopeSchema } from '../vault/crypto';
const uuid=z.string().uuid();
export class VaultError extends Error {constructor(public status:number,message:string){super(message);}}
export function reply(data:unknown,status=200){return Response.json(data,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});}
export function failure(e:unknown){return reply({error:e instanceof VaultError?e.message:'Не удалось выполнить запрос.',code:e instanceof VaultError?`VAULT_${e.status}`:'VAULT_UNAVAILABLE'},e instanceof VaultError?e.status:503);}
function credential(req:Request){const auth=req.headers.get('Authorization')??'';if(!/^Bearer [A-Za-z0-9_-]{43}$/.test(auth))throw new VaultError(401,'Недействительный ключ доступа.');return createHash('sha256').update(auth.slice(7)).digest('hex');}
function origin(req:Request){if(req.headers.get('Origin')!==new URL(process.env.APP_ORIGIN??'http://localhost:3000').origin)throw new VaultError(403,'Недопустимый источник запроса.');}
async function body(req:Request){const reader=req.body?.getReader();if(!reader)throw new VaultError(400,'Нет данных.');const chunks:Uint8Array[]=[];let size=0;try{for(;;){const {value,done}=await reader.read();if(done)break;size+=value.length;if(size>9*1024*1024){await reader.cancel();throw new VaultError(413,'Сейф слишком большой.');}chunks.push(value);}}finally{reader.releaseLock();}const all=new Uint8Array(size);let at=0;for(const c of chunks){all.set(c,at);at+=c.length;}try{return JSON.parse(new TextDecoder().decode(all));}catch{throw new VaultError(400,'Некорректный формат.');}}
export async function createVault(req:Request){origin(req);const hash=credential(req);const result=z.object({id:uuid,envelope:envelopeSchema}).strict().safeParse(await body(req));if(!result.success)throw new VaultError(400,'Некорректный зашифрованный пакет.');const {id,envelope}=result.data;const r=await databasePool().query('INSERT INTO vaults(id,auth_verifier_hash,encrypted_blob,version,schema_version) VALUES($1,$2,$3,1,1) ON CONFLICT DO NOTHING RETURNING version',[id,hash,JSON.stringify(envelope)]);if(!r.rows.length)throw new VaultError(409,'Сейф уже существует.');return reply({id,version:1},201);}
export async function accessVault(req:Request,id:string){if(!uuid.safeParse(id).success)throw new VaultError(404,'Сейф не найден.');const hash=credential(req);const r=await databasePool().query('SELECT auth_verifier_hash,encrypted_blob,version FROM vaults WHERE id=$1',[id]);const row=r.rows[0];if(!row)throw new VaultError(404,'Сейф не найден или удалён.');if(!timingSafeEqual(Buffer.from(hash,'hex'),Buffer.from(String(row.auth_verifier_hash),'hex')))throw new VaultError(401,'Не удалось открыть сейф.');return row;}
export async function getVault(req:Request,id:string){const row=await accessVault(req,id);return reply({id,version:Number(row.version),envelope:JSON.parse(String(row.encrypted_blob))});}
export async function putVault(req:Request,id:string){origin(req);await accessVault(req,id);const data=z.object({expectedVersion:z.number().int().positive().max(2147483646),envelope:envelopeSchema}).strict().safeParse(await body(req));if(!data.success)throw new VaultError(400,'Некорректный зашифрованный пакет.');const r=await databasePool().query('UPDATE vaults SET encrypted_blob=$1,version=version+1,updated_at=now() WHERE id=$2 AND version=$3 RETURNING version',[JSON.stringify(data.data.envelope),id,data.data.expectedVersion]);if(!r.rows.length)throw new VaultError(409,'На другом устройстве есть более новая версия данных.');return reply({version:Number(r.rows[0].version)});}
export async function deleteVault(req:Request,id:string){origin(req);await accessVault(req,id);await databasePool().query('DELETE FROM vaults WHERE id=$1',[id]);return reply({deleted:true});}
