import {test} from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {readFileSync,readdirSync} from 'node:fs';import {deleteImportedData} from '../lib/server/data.ts';import type {Database,Statement} from '../lib/server/db.ts';
test('data deletion is user scoped, keeps manual expenses, migration enforces deduplication',async()=>{const sqlite=new DatabaseSync(':memory:');sqlite.exec('PRAGMA foreign_keys=ON');for(const file of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sqlite.exec(readFileSync('drizzle/'+file,'utf8'));sqlite.exec("INSERT INTO users VALUES ('a','2026'),('b','2026')");
 const insert=sqlite.prepare("INSERT INTO recurring_expenses (id,user_id,name,type,amount_minor,currency,billing_period,status,source,created_at,updated_at) VALUES (?,?,?,'other',100,'RUB','monthly','active',?,'2026','2026')");
 insert.run('manual','a','Manual','manual');insert.run('detected','a','Detected','detected');insert.run('private','b','Private','detected');
 sqlite.exec("INSERT INTO transaction_imports (id,user_id,filename,format,status,created_at) VALUES ('i','a','a.csv','csv','completed','2026'),('j','b','b.csv','csv','completed','2026')");
 const tx=sqlite.prepare("INSERT INTO transactions (id,user_id,original_merchant,normalized_merchant,amount_minor,currency,paid_at,source_import_id,fingerprint,occurrence) VALUES (?,?,'m','m',100,'RUB','2026-01-01',?,'hash',0)");tx.run('t','a','i');assert.throws(()=>tx.run('dupe','a','i'));tx.run('private-t','b','j');
 class Stmt{sql:string;values:unknown[];constructor(sql:string,values:unknown[]=[]){this.sql=sql;this.values=values}bind(...values:unknown[]){return new Stmt(this.sql,values)}async run(){return sqlite.prepare(this.sql).run(...this.values as never[])}async all<T>(){return {results:sqlite.prepare(this.sql).all(...this.values as never[]) as T[]}}async first<T>(){return sqlite.prepare(this.sql).get(...this.values as never[]) as T|null}}
 const db:Database={prepare:(sql)=>new Stmt(sql),batch:async(stmts)=>{sqlite.exec('BEGIN');try{const results=[];for(const s of stmts)results.push(await s.run());sqlite.exec('COMMIT');return results}catch(e){sqlite.exec('ROLLBACK');throw e}}};
 await deleteImportedData(db,'a');assert.deepEqual(sqlite.prepare('SELECT id FROM recurring_expenses ORDER BY id').all().map(r=>r.id),['manual','private']);assert.deepEqual(sqlite.prepare('SELECT id FROM transactions').all().map(r=>r.id),['private-t']);assert.equal(sqlite.prepare("SELECT COUNT(*) AS n FROM transaction_imports WHERE user_id='a'").get()?.n,0);sqlite.close()});
