from pathlib import Path
p=Path('.')
f=p/'components/product/import-form.tsx';s=f.read_text(encoding='utf-8-sig').replace('<div className="import-layout">','{error&&pdfPreview&&<div role="alert" className="error-box">{error}</div>}<div className="import-layout">');s=s.replace('setResult(null);setFile(null)}}>Загрузить ещё', 'setResult(null);setFile(null);setPdfPreview(null)}}>Загрузить ещё');s=s.replace('>Найти мои расходы<ArrowRight', ">{file?.name.toLowerCase().endsWith('.pdf')?'Прочитать PDF':'Найти мои расходы'}<ArrowRight");f.write_text(s,encoding='utf-8')
f=p/'components/product/expense-list.tsx';s=f.read_text(encoding='utf-8-sig').replace("import {useState} from 'react';", "import {useState} from 'react';import {ServiceLogo} from './service-logo';import {advanceTo,today} from '@/lib/domain/calendar';");s=s.replace('const filtered=expenses.filter', "const filtered=expenses.map(e=>({...e,nextPaymentAt:e.nextPaymentAt&&e.status==='active'?advanceTo(e.nextPaymentAt,e.billingPeriod,today(),e.anchorDay,e.customDays):e.nextPaymentAt})).filter");s=s.replace('<span className="service-logo">{e.name[0]}</span>','<ServiceLogo name={e.name} serviceId={e.serviceId} type={e.type}/>');f.write_text(s,encoding='utf-8')
f=p/'components/product/expense-form.tsx';s=f.read_text(encoding='utf-8-sig').replace("import {Plus,PenLine}", "import {services} from '@/lib/domain/catalog';\nimport {Plus,PenLine}");s=s.replace('<div className="form-grid"><label', '<div className="form-grid"><div className="form-field full"><label>Известный сервис (необязательно)</label><SelectField label="Сервис" value={form.serviceId} onChange={v=>{const service=services.find(s=>s.id===v);setForm(s=>({...s,serviceId:v,...(service?{name:s.name||service.name,type:service.category}:{})}))}} options={[{value:\'\',label:\'Свой расход\'},...services.map(s=>({value:s.id,label:s.name}))]}/></div><label');f.write_text(s,encoding='utf-8')
f=p/'lib/domain/validation.ts';s=f.read_text(encoding='utf-8-sig');s="import {serviceById} from './catalog.ts';\n"+s;s=s.replace("const serviceId=typeof x.serviceId==='string'&&x.serviceId?x.serviceId:null;", "const serviceId=typeof x.serviceId==='string'&&x.serviceId?x.serviceId:null;if(serviceId&&!serviceById(serviceId))throw new Error('Выберите сервис из каталога.');");f.write_text(s,encoding='utf-8')
f=p/'lib/server/candidates.ts';s=f.read_text(encoding='utf-8-sig');s="import {median} from '../domain/detection';\n"+s;needle=' const decisions=await db().prepare';refresh=""" for(const e of expenses.filter(e=>e.status==='active')){const linked=all.filter(t=>t.recurringExpenseId===e.id).sort((a,b)=>a.paidAt.localeCompare(b.paidAt));const last=linked[linked.length-1];if(!last||last.sourceImportId!==importId)continue;const amount=e.type==='utility'?median(linked.slice(-4).map(t=>t.amountMinor)):last.amountMinor;const next=advanceTo(addPeriod(last.paidAt,e.billingPeriod,1,e.anchorDay,e.customDays),e.billingPeriod,today(),e.anchorDay,e.customDays);await db().prepare('UPDATE recurring_expenses SET amount_minor=?,next_payment_at=?,updated_at=? WHERE id=? AND user_id=? AND status=?').bind(amount,next,new Date().toISOString(),e.id,userId,'active').run();}
""";s=s.replace(needle,refresh+needle);f.write_text(s,encoding='utf-8')
f=p/'lib/server/expenses.ts';s=f.read_text(encoding='utf-8-sig').replace(" const previous=id?", " if(!id){const count=await db().prepare('SELECT COUNT(*) AS n FROM recurring_expenses WHERE user_id=?').bind(userId).first<{n:number}>();if((count?.n??0)>=500)throw new ApiError(400,'Лимит MVP — 500 расходов.');}\n const previous=id?");f.write_text(s,encoding='utf-8')
